name: Check Service Status

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the service URL
        run: curl --fail --silent --show-error https://123.60.91.241:2333/ || exit 1
